# -*- coding: utf-8 -*-
"""Project_music.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q3Z9Azzevi_XHFC-56_7Sbbhn3lPRhqv
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler
from sklearn.impute import SimpleImputer
from sklearn.feature_selection import mutual_info_classif
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score
from sklearn.cluster import KMeans
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from sklearn.model_selection import cross_val_score
from sklearn.feature_selection import RFECV

from google.colab import drive
drive.mount('/content/drive', force_remount = True)
tracks = pd.read_csv('/content/drive/MyDrive/ДАТАСЕТЫ/default_features_1059_tracks.txt')
plusTracks = pd.read_csv('/content/drive/MyDrive/ДАТАСЕТЫ/default_plus_chromatic_features_1059_tracks.txt')

"""**Объединение датасетов и их форматирование**"""

#Дублирование имен столбцов в новую строку в первом датасете
tracks = tracks.astype(object)

empty_row = pd.DataFrame([[np.nan]*len(tracks.columns)], columns=tracks.columns)
tracks = pd.concat([empty_row, tracks], ignore_index=True)

for j in tracks.columns:
    if pd.isna(tracks.loc[0, j]):
        tracks.loc[0, j] = j

print("Дублирование имен столбцов в новую строку в первом датасете:")
tracks

#Дублирование имен столбцов в новую строку во втором датасете
plusTracks = plusTracks.astype(object)

empty_row = pd.DataFrame([[np.nan]*len(plusTracks.columns)], columns=plusTracks.columns)
plusTracks = pd.concat([empty_row, plusTracks], ignore_index=True)

for j in plusTracks.columns:
    if pd.isna(plusTracks.loc[0, j]):
        plusTracks.loc[0, j] = j

print("Дублирование имен столбцов в новую строку во втором датасете:")
plusTracks

#Переименование последних двух столбцов датасетов
rename_dict = {"-15.75": "Широта", "-47.95": "Долгота"}

tracks.rename(columns=rename_dict, inplace=True)
plusTracks.rename(columns=rename_dict, inplace=True)

print("Названия столбцов после переименования последних двух первого датасета:")
print(tracks.columns)
print()
print("Названия столбцов после переименования последних двух второго датасета:")
print(plusTracks.columns)

#Объединение датасетов и добавление широты и долготы в конец датасета
dataSet = tracks.merge(plusTracks, how='outer')

cols = list(dataSet.columns)
cols.remove("Широта")
cols.remove("Долгота")

cols += ["Широта", "Долгота"]

dataSt = dataSet[cols]

print(dataSt.columns)

#Дубликаты
for col in dataSt.columns:
    if dataSt[col].dtype == 'object':
        dataSt[col] = pd.to_numeric(dataSt[col], errors='coerce')
print(dataSt.dtypes)

duplicates = []
columns = dataSt.columns

for i in range(len(columns)):
    for j in range(i + 1, len(columns)):
        if dataSt[columns[i]].equals(dataSt[columns[j]]):
            duplicates.append((columns[i], columns[j]))

print("Дублирующиеся столбцы:","\n", duplicates)

#Удаление дубликатов
cols_to_drop = []
for dup in duplicates:
    cols_to_drop.append(dup[1])
cols_to_drop = set(cols_to_drop)

dataSt = dataSt.drop(columns=cols_to_drop)

print("Оставшиеся столбцы:","\n", dataSt.columns)

#Переименование всех столбцов, кроме двух последних
dataSt.columns = ["Признак " + str(i) for i in range(len(dataSt.columns))]


cols = list(dataSt.columns)

cols[-2] = "Широта"
cols[-1] = "Долгота"

dataSt.columns = cols

print("Названия столбцов после переименования:")
dataSt

"""**1.** **Выполнить кодирование дискретных переменных(создание категориального столбца)**"""

#Определение количества кластеров
coords = dataSt[['Широта', 'Долгота']]
inertia = []
k_range = range(1, 15)

for k in k_range:
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(coords)
    inertia.append(kmeans.inertia_)  # Сумма квадратов расстояний внутри кластеров


plt.plot(k_range, inertia, marker='o')
plt.xlabel('Количество кластеров (k)')
plt.ylabel('Сумма внутрикластерных расстояний')
plt.title('Метод локтя')
plt.axvline(x=5, color='r', linestyle='--', label='Пример локтя при k=5')
plt.show()

#Выбранное количество кластеров; Создание категориального столбца

k = 4
kmeans = KMeans(n_clusters=k, random_state=42)
dataSt['Целевая переменная'] = kmeans.fit_predict(dataSt[['Широта', 'Долгота']])
dataSt = dataSt.drop(columns=['Широта', 'Долгота'])
dataSt
print(dataSt['Целевая переменная'])

# Подсчёт количества объектов в каждом кластере
unique, counts = np.unique(dataSt['Целевая переменная'], return_counts=True) #unique находит уникальные метки кластеров и считает, сколько точек относится к каждому кластеру
cluster_sizes = dict(zip(unique, counts))

weights = np.array([1 / cluster_sizes[label] for label in dataSt['Целевая переменная']])

kmeans_weighted = KMeans(n_clusters=k, random_state=42) #новая модель KMeans
kmeans_weighted.fit(coords, sample_weight=weights)

weighted_labels = kmeans_weighted.labels_

# Добавляем категориальный столбец с новыми метками кластеров
dataSt['Целевая переменная'] = weighted_labels
dataSt

print(dataSt['Целевая переменная'])

"""**2. По каждому признаку и целевой переменной надо построить график и гистограмму**"""

#График
sampled_dataSt = dataSt.sample(frac=0.05, random_state=12)

for col in sampled_dataSt.columns:
    if col != 'Целевая переменная':
        plt.figure(figsize=(6, 4))
        sns.boxplot(x=sampled_dataSt['Целевая переменная'], y=sampled_dataSt[col])
        plt.xlabel('Целевая переменная')
        plt.ylabel(col)
        plt.show()
    else:
        break

#Гистограмма
for col in dataSt.columns:
    plt.figure(figsize=(6, 4))
    dataSt[col].plot.hist(bins=30, alpha=0.7, edgecolor='black')
    plt.xlabel(col)
    plt.ylabel('Частота')
    plt.grid(axis='y')
    plt.show()

#Обработка аномальных значений(не дает никакого результата)
#for col in dataSt.columns:
    #if col != 'Целевая переменная':
        #Q1 = dataSt[col].quantile(0.25)
        #Q3 = dataSt[col].quantile(0.75)
        #IQR = Q3 - Q1
        #lower_bound = Q1 - 3 * IQR
        #upper_bound = Q3 + 3 * IQR

        #dataSt = dataSt[(dataSt[col] >= lower_bound) & (dataSt[col] <= upper_bound)]

"""**3. Надо посчитать статистики по каждой переменной, количество и распределение пропусков**"""

#Статистика
dataSt.describe()

#Информация о пропусках и их количество
dataSt.info()
dataSt.isnull().sum()

"""**4. Обработать пропуски данных**"""

columns = dataSt.columns

imputer = SimpleImputer(strategy='mean')
dataSt_imputed = imputer.fit_transform(dataSt)

dataSt = pd.DataFrame(dataSt_imputed, columns=columns)

dataSt.isnull().sum()

"""**5. Нормализовать или стандартизировать признаки (целевую переменную)**"""

#Нормализация
features = dataSt.iloc[:, :-1]
target = dataSt['Целевая переменная']

scaler = MinMaxScaler()
features_norm = pd.DataFrame(scaler.fit_transform(features), columns=features.columns) #fit_transform() сначала вычисляет минимумы и максимумы по каждому признаку, а затем масштабирует данные.

dataSt = pd.concat([features_norm, target.reset_index(drop=True)], axis=1)
dataSt['Целевая переменная'] = dataSt['Целевая переменная'].astype(int)

dataSt

"""**6. Исследование зависимости пар признаков и признак-целевая переменная. Строим график, считаем матрицу корреляций, считаем взаимную информацию**"""

#График
sampled_dataSt = dataSt.sample(frac=0.05, random_state=12)

for col in sampled_dataSt.columns:
    if col != 'Целевая переменная':
        plt.figure(figsize=(6, 4))
        sns.boxplot(x=sampled_dataSt['Целевая переменная'], y=sampled_dataSt[col])
        plt.xlabel('Целевая переменная')
        plt.ylabel(col)
        plt.show()
    else:
        break

#Матрица корреляций
correlation_matrix = dataSt.corr()
correlation_matrix

#Взаимная информация(график) - показывает, насколько знание одной переменной уменьшает неопределённость о другой, учитывая любые зависимости — и линейные, и нелинейные.
features = dataSt.iloc[:, :-1]
target = dataSt['Целевая переменная']

mi = mutual_info_classif(features, target, random_state=42)

mi_series = pd.Series(mi, index=features.columns)
mi_series = mi_series.sort_values(ascending=False)

plt.figure(figsize=(14, 5))
mi_series.plot(kind='bar', color='blue')
plt.title('Взаимная информация признаков')
plt.ylabel('MI')
plt.xlabel('Признаки')
plt.xticks(rotation=90, ha='right')

plt.show()

#Взаимная информация(таблица)
features = dataSt.iloc[:, :-1]
target = dataSt['Целевая переменная']

mi = mutual_info_classif(features, target)

print("Взаимная информация:", "\n", mi)

#Удаление столбцов, у которых взаимная информация равна 0
dataSt = dataSt.drop(['Признак 28', 'Признак 57', 'Признак 61', 'Признак 28'], axis=1)

"""**7. Строим модели для решения задачи разного типа. Оцениваем точность (использовать 2 метрики)**"""

#Оценка точности(НЕлинейная модель) и оценка матрицы классификаций
features = dataSt.iloc[:, :-1]
target = dataSt['Целевая переменная']

X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=42, stratify=target)

model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

y_model = model.predict(X_test)

acc = accuracy_score(y_test, y_model) #Доля правильно предсказанных объектов от общего числа объектов
f1 = f1_score(y_test, y_model, average='weighted') #Среднее между точностью (precision) и полнотой (recall)

print("Accuracy:", acc)
print("F1-score:", f1)

print()

#Матрица классификаций - на главной диагонали правильно предсказанные обьекты, вне матрицы - ошибочно предсказанные (строки - истинные классы, столбцы - предсказанные классы)
print("Матрица классификаций:")
cm = confusion_matrix(y_test, y_model)  # Вычисляет матрицу классификации (confusion matrix)

disp = ConfusionMatrixDisplay(confusion_matrix=cm)  # Создаёт объект для визуализации матрицы классификации

disp.plot()  # Строит график матрицы классификации

plt.show()  # Показывает график

#Оценка точности(линейная модель) и оценка матрицы классификаций
#логист. регрессия(суть)-сначала вычисляется линейная комбинация признаков с весами, затем результат пропускается через сигмоидальную функцию, которая даёт вероятность. Если вероятность выше порога, объект относят к положительному классу, иначе — к отрицательному
features = dataSt.iloc[:, :-1]
target = dataSt['Целевая переменная']

X_train, X_test, y_train, y_test = train_test_split(
    features, target, test_size=0.2, random_state=42, stratify=target
)

# Создание и обучение линейной модели логистической регрессии
model = LogisticRegression(random_state=42, max_iter=1000)
model.fit(X_train, y_train)

y_model = model.predict(X_test)

acc = accuracy_score(y_test, y_model)  # Доля правильно предсказанных объектов
f1 = f1_score(y_test, y_model, average='weighted')  # Среднее между точностью и полнотой

print("Accuracy:", acc)
print("F1-score:", f1)

print()

#Матрица классификаций
print("Матрица классификаций:")
cm = confusion_matrix(y_test, y_model)  # Вычисляет матрицу классификации (confusion matrix)

disp = ConfusionMatrixDisplay(confusion_matrix=cm)  # Создаёт объект для визуализации матрицы классификации

disp.plot()  # Строит график матрицы классификации

plt.show()  # Показывает график

"""**8. Подбираем гиперпараметры к модели. Оцениваем точность**"""

#Задаём несколько вариантов параметров для поиска(нелинейная модель)
param_grid = {'n_estimators': [76, 100, 123, 160, 190], 'max_depth': [None, 10, 20, 30, 40], 'min_samples_split': [2, 5, 4, 6], 'min_samples_leaf': [1, 2, 3, 4]}


grid_search = GridSearchCV(RandomForestClassifier(random_state=42), param_grid, cv=3, scoring='f1_weighted')

# Обучаем модель с подбором параметров
grid_search.fit(X_train, y_train)

# Лучшая модель
best_model1 = grid_search.best_estimator_
print("Лучшие параметры:", grid_search.best_params_)

# Оценка на тестовых данных
y_model = best_model1.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_model))
print("F1-score:", f1_score(y_test, y_model, average='weighted'))

#Задаём несколько вариантов параметров для поиска(линейная модель)
param_grid = {
    'C': [0.001, 0.01, 0.1, 1, 10, 100],          # Коэффициент регуляризации
    'penalty': ['l1', 'l2'],                       # Тип регуляризации (l1 - веса зануляются, l2 - уменьшает величину весов)
    'solver': ['liblinear', 'saga']                # Алгоритмы, поддерживающие l1 и l2
}

#Объект GridSearchCV с логистической регрессией
grid_search = GridSearchCV(
    LogisticRegression(max_iter=10000, random_state=42),
    param_grid,
    cv=5,
    scoring='f1_weighted',
    n_jobs=-1
)

# Обучаем модель с подбором параметров
grid_search.fit(X_train, y_train)

# Лучшая модель и параметры
best_model2 = grid_search.best_estimator_
print("Лучшие параметры:", grid_search.best_params_)

# Оценка на тестовых данных
y_model = best_model2.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_model))
print("F1-score:", f1_score(y_test, y_model, average='weighted'))

"""**9. Проводим оценку по кросс-валидации.  Оцениваем точность**"""

#Нелинейная модель
cv_acc = cross_val_score(best_model1, features, target, cv=5, scoring='accuracy')
cv_f1 = cross_val_score(best_model1, features, target, cv=5, scoring='f1_weighted')

print("Средняя accuracy (CV):", cv_acc.mean())
print("Средняя F1-score (CV):", cv_f1.mean())

#Линейная моедль
cv_acc = cross_val_score(best_model2, features, target, cv=5, scoring='accuracy')
cv_f1 = cross_val_score(best_model2, features, target, cv=5, scoring='f1_weighted')

print("Средняя accuracy (CV):", cv_acc.mean())
print("Средняя F1-score (CV):", cv_f1.mean())

"""**10. Убираем незначимые признаки с помощью кросс-валидации. Оцениваем точность - здесь одну модель? да**"""

selector = RFECV(estimator=best_model1, step=1, cv=5, scoring='f1_weighted', n_jobs=-1)
selector.fit(features, target)

print("Оптимальное число признаков:", selector.n_features_)
selected_features = features.columns[selector.support_] # selector.support_-булевый массив (маска) длиной равной числу признаков, где True означает, что данный признак был выбран (отобран) методом RFECV, а False — что признак исключён.

print("Выбранные признаки:", list(selected_features))

# Оцениваем модель с отобранными признаками
X_selected = features[selected_features]
cv_acc_sel = cross_val_score(best_model1, X_selected, target, cv=5, scoring='accuracy')
cv_f1_sel = cross_val_score(best_model1, X_selected, target, cv=5, scoring='f1_weighted')

print("Средняя accuracy после отбора признаков (CV):", cv_acc_sel.mean())
print("Средний F1-score после отбора признаков (CV):", cv_f1_sel.mean())

"""**11. Исследуем самую лучшую модель на важность/чувствительность признаков-здесь уже я выбираю одну модель? да**"""

# Обучаем модель на всех данных с выбранными признаками
best_model1.fit(X_selected, target)

importances = best_model1.feature_importances_
indices = np.argsort(importances)[::-1]

plt.figure(figsize=(10,6))
plt.title("Важность признаков")
plt.bar(range(len(selected_features)), importances[indices], align='center')
plt.xticks(range(len(selected_features)), [selected_features[i] for i in indices], rotation=90)
plt.tight_layout()
plt.show()